#!/usr/bin/env bash
#Write a Bash script that uses ssh to connect to your server usin#g the private key ~/.ssh/school with the user ubuntu.
#
#Requirements:
#
#Only use ssh single-character flags
#You cannot use -l
#You do not need to handle the case of a private key protected by #a passphrase
ssh -i ~/.ssh/school -o "User=ubuntu" -o "LogLevel=ERROR" -o "StrictHostKeyChecking=no" -o "BatchMode=yes" 54.173.88.192 exit

