#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line. Requirements: You must use the while loop (for and until are forbidden You must use the if statement
count=0
while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
		echo "Best School"
		(( count++ ))
done
