#!/usr/bin/env bash
#This script is displaying number from 1-20 but "displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration
#Requirements:
#
#You must use the while loop (for and until are forbidden)
#You must use the case statement" 10 times
#down is the solution 
i=1
while [ "$i" -le 20 ]
do
    echo "$i"
    case $i in
        "4") echo "bad luck from China"
        ;;
        "9") echo "bad luck from Japan"
        ;;
        17)echo "bad luck from Italy"
        ;;
    esac

    (( i++ ))
done
