#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
#
#display hours from 0 to 12
#display minutes from 1 to 59
#Requirements:
#
#You must use the while loop (for and until are forbidden)
#Note that in this example, we only display the first 70 lines using the head command.
i=1
j=0
while [ "$j" -le 12 ]
do
    echo "Hour: $j"
    i=1
    while [ "$i" -le 59 ]
    do
        echo "$i"
	(( i++ ))
    done
    (( j++ ))
done
