#!/usr/bin/env bash
#Write a Bash script that configures an Ubuntu server with the below requirements.
#
#Requirements:
#
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
#The checker is running on Docker, so make sure to read this
#In this example we can see that:
#
#before running the script, localhost resolves to 127.0.0.1 and facebook.com resolves to 157.240.11.35
#after running the script, localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8
#If you’re running this script on a machine that you’ll continue to use, be sure to revert localhost to 127.0.0.1. Otherwise, a lot of things will stop working!
cp /etc/hosts ~/hosts.new
sed -i 's/^127.0.0.1.*/127.0.0.2 localhost/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts

