#!/usr/bin/env bash
#Write a Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.
#
#Requirements:
#
#Only use ssh single-character flags
#You cannot use -l
#You do not need to handle the case of a private key protected wor#h a passphrase
ssh -o User=ubuntu -o LogLevel=QUIET -o StrictHostKeyChecking=no -o BatchMode=yes -o IdentityFile=~/.ssh/school ubuntu@8.8.8.8 exit

